### ISSUE TITLE
This needs a publish to npm

### ISSUE THREAD

**Issue by kanongil** [hapijs/lab-external-module-test#7]
The current release is a year old, and references a deprecated version of @hapi/pinpoint.

**Comment by devinivy** [comment]
Good call, on it.

**Comment by devinivy** [comment]
Upon further inspection this calls for a major release due to the node support of dependencies.  Looks like @cjihrig and @lloydbenson were looped-in on some of those changes.  Just looking for a gut check and 👍 to publish the latest as 2.0.0.

https://github.com/hapijs/lab-external-module-test/milestone/4?closed=1

**Comment by cjihrig** [comment]
Isn't this only used for lab's test suite? I think it's fine to publish a new version.

**Comment by devinivy** [comment]
Done!

**Comment by kanongil** [comment]
The `@hapi/pinpoint` module is still deprecated with the new release:

```
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
```
